[package]
distribution = "slbeta6"
org= "ballerinax"
name= "microsoft.outlook.mail"
version= "2.1.0"
authors = ["Ballerina"]
keywords = ["Communication/Email", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.mail"
license = ["Apache-2.0"]

[build-options]
observability-included=true
